schemaVersion: 2.3.0
metadata:
  name: jumpstarter-dev
  icon: https://jumpstarter.dev/jumpstarter.svg
  tags:
    - Python
    - UV
    - Jumpstarter
  language: Python
projects:
  - name: jumpstarter
    git:
      remotes:
        origin: https://github.com/rhadp-example-repos/jumpstarter.git
components:
  - name: runtime
    container:
      image: registry.redhat.io/devspaces/udi-rhel9:3.19
      volumeMounts:
        - name: venv
          path: /home/user/.venv
      memoryLimit: "4Gi"
      memoryRequest: "1Gi"
      cpuLimit: "4"
      cpuRequest: "1"
      mountSources: true
  - name: venv
    volume:
      size: 1G
commands:
  - id: clean
    exec:
      component: runtime
      commandLine: make clean
  